jobs:
- job: ci_iac

  pool:
    vmImage: 'ubuntu-latest'
  
  steps:
  - task: CopyFiles@2
    displayName: 'Copy Files to: $(Build.ArtifactStagingDirectory)'
    inputs:
      SourceFolder: '$(Build.SourcesDirectory)'
      Contents: |
        **/*
        !.git/**/*
        !.gitignore
        !Pipelines/**/*
      TargetFolder: '$(Build.ArtifactStagingDirectory)'
  
  - task: PublishBuildArtifacts@1
    displayName: 'Publish Artifact: drop'
